### PR TITLE
updated with configuration of flowlogs2metrics

### PR DESCRIPTION
**Pull request by eranra**

### CODE REVIEW

**Comment by jotak** [comment]
We don't want to filter every field based on a white list like proposed here, at least it's not like it currently works in goflow-kube. The reason is that, in the console plugin, we let the user see the whole json flows, even for columns that we are not displaying, which could eventually be useful for debugging, I think. We make a kind of "editorial choice" when displaying columns, and want to leave the full json access available in case there's interesting data not covered.

**Comment by eranra** [comment]
@KalmanMeth what will happen if we remove the `transform generic` stage ... will we get all the fields???  

https://github.com/jotak/network-observability-operator/pull/1/files#diff-0e93448aad33d45e855f64ad3d30474ea7552dae691a53784c0396d6f27605f1R251

**Comment by KalmanMeth** [comment]
> @KalmanMeth what will happen if we remove the `transform generic` stage ... will we get all the fields???
> 
> https://github.com/jotak/network-observability-operator/pull/1/files#diff-0e93448aad33d45e855f64ad3d30474ea7552dae691a53784c0396d6f27605f1R251

@eranra If you use transform none, then it should simply give you everything. If there is no transform generic but there is transform network, then you'll get whatever the transform network outputs.

**Comment by eranra** [comment]
@jotak I updated the PR - removed ` transform generic` and we should get all the fields (no white listing)

**Comment by jotak** [comment]
thanks!

**Pull request merged**
